@startuml chapter020_020_image_sequence

/' ---------------------------------------------- '/
' 固定エリア

'ヘッダー
header

<font color=red>公開</font>


endheader


'フッター
right footer


<b>Copyright &#169; 2023 takashno All Right Reserved.</b>　
endfooter

/' ---------------------------------------------- '/
' スタイルエリア

'必要なら追加
skinparam {
defaultFontName Meiryo
ArrowColor black
Shadow none
shadowing false
'linetype ortho
}
skinparam sequence {
ActorBorderColor black
LifeLineBorderColor black
LifeLineBackgroundColor black
ParticipantBorderColor black
ParticipantBackgroundColor black
}
skinparam participant {
BackgroundColor White
BorderColor Black
}
skinparam actor {
BackgroundColor White
BorderColor Black
}
skinparam note {
BackgroundColor #dcf8f8
BorderColor Black
}

/' ---------------------------------------------- '/
' 描画エリア

' 参考
' http://plantuml.com/sequence-diagram


Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response

@enduml
